http:
  addr: :8000
  auth:
    username: "alertmanager"
    password: "verysecure"
ntfy:
  baseurl: https://ntfy.sh
  auth:
    basic:
      username: "admin"
      password: "verysecure"
    # OR
    token: "verysecureauthtoken"
  notification:
    # The topic can either be a hardcoded string or a gval expression that evaluates to a string
    topic: alertmanager
    # Priority reference: https://docs.ntfy.sh/publish/#message-priority
    # Can either be a hardcoded string or a gval expression that evaluates to a string
    priority: |
      status == "firing" ? "urgent" : "default"
    tags:
      # Tags with no condition are always included
      # Emoji shortcode reference: https://docs.ntfy.sh/emojis/
      - tag: "+1"
        condition: status == "resolved"
      - tag: rotating_light
        condition: status == "firing"
    templates:
      title: |
        {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
      description: |
        {{ index .Annotations "description" }}
      # Labels template - controls how alert labels are converted to ntfy tags
      # If not specified, defaults to: {{range $key, $value := .}}{{$key}} = {{$value}}, {{end}}
      labels: |
        {{range $key, $value := .}}{{$key}} = {{$value}}{{end}}
      # Alternative examples:
      #
      # Empty template to disable label tags entirely:
      # labels: ""
      #
      # Custom format with colons instead of equals:
      # labels: |
      #   {{range $key, $value := .}}{{$key}}: {{$value}}{{end}}
      #
      # Complex conditional template to only show specific labels:
      # labels: |
      #   {{- range $key, $value := . -}}
      #     {{- if and (ne $key "internal_label") (ne $key "debug_info") -}}
      #       {{ $key }}={{ $value }}
      #     {{- end -}}
      #   {{- end -}}
      #
      # Or show labels only if severity is high:
      # labels: |
      #   {{- if eq (index . "severity") "critical" -}}
      #     {{- range $key, $value := . -}}
      #       {{ $key }}={{ $value }}
      #     {{- end -}}
      #   {{- end -}}
      headers:
        X-Click: |
          {{ .GeneratorURL }}
